NYT article page project
mohapakram/New-York-Times-article-page-clone pull request #2
Opened 2020-06-16 14:20 UTC by nusretbutunay

This assignment consists of making a clone of a New York Times article page.

2020-06-16 17:44 UTC, andresporras3423 commented
### **Pull Request Under Review By Oscar Russi (TSE)**

2020-06-16 17:59 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello @nusretbutunay @mohapakram** 
Good job with your first submission for this project :muscle:  
your page looks really similar to the original :clap: :clap: :clap:  
Your project passes most of the requirements. There are just a few details to improve before you can go ahead:
- [ ] Don't overuse ID Selectors
- [ ] Don't repeat yourself, in order to minimize code you can group selectors with the same style definition (in your CSS files).
- [x]  Check over the "editors pick" in the original page and in your page. In the original:


![](https://i.imgur.com/bO8Ym7fl.png)

In your page:

![](https://i.imgur.com/GoGUeocl.png)

Add the "Subscribe to The Times" section.

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras
(for any question you can contact me in slack as @oscarporras02)

2020-06-16 17:59 UTC, andresporras3423 commented on style.css
> +#inflation-grid-container span {
Don't overuse ID Selectors

2020-06-16 17:59 UTC, andresporras3423 commented on style.css
> +}
Don't repeat yourself, in order to minimize code you can group selectors with the same style definition (in your CSS files).

2020-06-16 17:59 UTC, andresporras3423 commented on style.css
> +}
Don't repeat yourself, in order to minimize code you can group selectors with the same style definition (in your CSS files).

2020-06-16 17:59 UTC, andresporras3423 commented on style.css
> +#video {
Don't overuse ID Selectors

2020-06-16 17:59 UTC, andresporras3423 commented on style.css
> +}
You have a similar style in another selector on line 219

2020-06-17 09:28 UTC, trekab approved these changes
# Approved! :tada: 
Hi @nusretbutunay and @mohapakram! Well done! :+1: You may merge to master, submit the project completion form, and proceed to your next project.

All the best on your next project! :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

2020-06-17 09:30 UTC, merged